[build-system]
requires = ["setuptools>=68", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "brofopy"
version = "0.1.0"
description = "Read Bronformat data with SciPy, convert to Pandas DataFrames and HydroPandas ObsCollections."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
maintainers = [
    { name = "J. R. von Asmuth", email = "jos.von.asmuth@3hydro.nl" },
]
authors = [
    { name = "M.A. Vonk", email = "m.vonk@artesia-water.nl" },
    { name = "R. Calje", email = "r.calje@artesia-water.nl" },
    { name = "J. R. von Asmuth", email = "jos.von.asmuth@3hydro.nl" },
    { name = "D. Krijnders", email = "dirkjan.krijnders@anteagroup.nl" },
]
requires-python = ">=3.11"
dependencies = [
    "scipy>=1.16.0",
    "pandas>=2.0",
    "hydropandas>=0.18.0",
    "brodata>=0.1.0",
]
classifiers = [
    'Programming Language :: Python :: 3 :: Only',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
]

[project.optional-dependencies]
dev = ["pytest", "pytest-cov", "ruff", "ty", "pre-commit"]
docs = ["sphinx", "sphinx-rtd-theme", "myst-parser"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
src = ["src"]
extend-include = ["*.ipynb"]
show-fixes = true
fix = true

[tool.ruff.lint]
extend-select = ["I", "D"]
pydocstyle.convention = "numpy"
