[build-system]
requires = ["setuptools>=68", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "brofopy"
dynamic = ["version"]
description = "Read Bronformat data with SciPy, convert to Pandas DataFrames and HydroPandas ObsCollections."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
maintainers = [{ name = "J.R. von Asmuth", email = "jos.von.asmuth@3hydro.nl" }]
authors = [
    { name = "J.R. von Asmuth", email = "jos.von.asmuth@3hydro.nl" },
    { name = "M.A. Vonk", email = "m.vonk@artesia-water.nl" },
    { name = "R. Calje", email = "r.calje@artesia-water.nl" },
]
requires-python = ">=3.11"
dependencies = [
    "scipy>=1.16.0",
    "pandas>=2.0",
    "hydropandas>=0.18.0",
    "h5py>=3.16.0",
]
classifiers = [
    'Programming Language :: Python :: 3 :: Only',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Programming Language :: Python :: 3.14',
]

[project.optional-dependencies]
dev = ["brofopy[docs,tests]", "pre-commit"]
tests = ["pytest", "pytest-cov", "ruff"]
docs = ["sphinx", "sphinx-rtd-theme", "myst-parser", "ipykernel", "nbsphinx"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
version = { attr = "brofopy._version.__version__" }

[tool.ruff]
src = ["src"]
extend-include = ["*.ipynb"]
show-fixes = true
fix = true

[tool.ruff.lint]
extend-select = ["I", "D"]
pydocstyle.convention = "numpy"
